In [1]:
input_annotations_file = './converted_8_coordinate_test_annotations_pascal_VOC_format.txt'

In [2]:
# all imports

import pandas as pd
import numpy as np
import math
import ast

In [3]:
# Convert Annotations to csv without headers aka column names

with open(input_annotations_file,'r') as f:
    annotations = f.readlines()

f.close()

# remove spaces and new line attribute
annotations = [ann.strip() for ann in annotations]

In [4]:
annotations = [ann.replace(" ", ",") for ann in annotations]

In [5]:
annotations = [ann.split(",") for ann in annotations]

In [6]:
ann_df = pd.DataFrame(data = annotations)

In [7]:
no_of_boxes = (len(ann_df.columns)-1) // 9

In [8]:
no_of_boxes

62

In [9]:
col = ['name']

for i in range(1, no_of_boxes+1):
    
    x1='x1'+ str(i)
    y1='y1'+ str(i)
    
    x2='x2'+ str(i)
    y2='y2'+ str(i)
    
    x3='x3'+ str(i)
    y3='y3'+ str(i)
    
    x4='x4'+ str(i)
    y4='y4'+ str(i)
    
    class_name = 'class'+str(i)
    

    col.append(x1)
    col.append(y1)
    
    col.append(x2)
    col.append(y2)
    
    col.append(x3)
    col.append(y3)
    
    col.append(x4)
    col.append(y4)
    
    col.append(class_name)

In [10]:
ann_df.columns = col

In [11]:
ann_df.sort_values(by='name', inplace = True)
ann_df.reset_index(inplace=True)
ann_df.drop(columns=['index'], inplace=True)

In [12]:
for col in ann_df.columns.to_list()[1:]:
    
    ann_df[col] = ann_df[col].astype(float)

In [13]:
ann_df.head()

,name,x11,y11,x21,y21,x31,y31,x41,y41,class1,...,class61,x162,y162,x262,y262,x362,y362,x462,y462,class62
0,C1_P02_N1_S5_1.JPG,1032.0,2080.0,1204.0,2080.0,1204.0,2408.0,1032.0,2408.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C1_P02_N2_S2_1.JPG,1088.0,1632.0,1428.0,1632.0,1428.0,2216.0,1088.0,2216.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C1_P02_N2_S3_1.JPG,1228.0,1876.0,1548.0,1876.0,1548.0,2396.0,1228.0,2396.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C1_P03_N1_S2_1.JPG,1020.0,388.0,1236.0,388.0,1236.0,680.0,1020.0,680.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C1_P03_N1_S3_1.JPG,100.0,904.0,268.0,904.0,268.0,1220.0,100.0,1220.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# for i in range(1, no_of_boxes+1):
    
#     x1='x1'+ str(i)
#     y1='y1'+ str(i)
        
#     x2='x2'+ str(i)
#     y2='y2'+ str(i)
        
#     x3='x3'+ str(i)
#     y3='y3'+ str(i)
        
#     x4='x4'+ str(i)
#     y4='y4'+ str(i)
        
#     ann_df['dim_np'+str(i)+'_x'] = ann_df.apply(lambda row : calculateDistance(row[x1], row[y1], row[x2], row[y2]) , axis = 1)
#     ann_df['dim_np'+str(i)+'_y'] = ann_df.apply(lambda row : calculateDistance(row[x1], row[y1], row[x4], row[y4]), axis = 1)

In [15]:
df_new = pd.DataFrame(columns=['name','bounding_box_no','x1','y1','x2','y2','x3','y3','x4','y4','class'])

In [16]:
df_new

Empty DataFrame
Columns: [name, bounding_box_no, x1, y1, x2, y2, x3, y3, x4, y4, class]
Index: []

In [17]:
for index, row in ann_df.iterrows():
   
    name = row['name']  
    
    for o in range(1,no_of_boxes+1): 
        
        x1 = 'x1'+ str(o)
        y1 = 'y1'+ str(o)
        
        x2 = 'x2'+ str(o)
        y2 = 'y2'+ str(o)
        
        x3 = 'x3'+ str(o)
        y3 = 'y3'+ str(o)
        
        x4 = 'x4'+ str(o)
        y4 = 'y4'+ str(o)
        
        class_name = 'class'+str(o)

        df_new = df_new.append({'name':name,
                                'bounding_box_no': o,
                                'x1' : row[x1],
                                'y1' : row[y1],
                                'x2' : row[x2],
                                'y2' : row[y2],
                                'x3' : row[x3],
                                'y3' : row[y3],
                                'x4' : row[x4],
                                'y4' : row[y4],
                                'class' : row[class_name]}, ignore_index=True)

In [18]:
df_new.dropna(axis = 0, inplace = True)

In [21]:
df_new.sort_values(by=['name','bounding_box_no'],  inplace=True)

In [23]:
df_new[df_new['name'] == 'C1_P02_N1_S5_1.JPG']

,name,bounding_box_no,x1,y1,x2,y2,x3,y3,x4,y4,class
0,C1_P02_N1_S5_1.JPG,1,1032.0,2080.0,1204.0,2080.0,1204.0,2408.0,1032.0,2408.0,0.0
1,C1_P02_N1_S5_1.JPG,2,1040.0,1092.0,1192.0,1092.0,1192.0,1392.0,1040.0,1392.0,0.0
2,C1_P02_N1_S5_1.JPG,3,1040.0,1600.0,1224.0,1600.0,1224.0,1892.0,1040.0,1892.0,0.0
3,C1_P02_N1_S5_1.JPG,4,1088.0,616.0,1236.0,616.0,1236.0,920.0,1088.0,920.0,0.0
4,C1_P02_N1_S5_1.JPG,5,1128.0,124.0,1308.0,124.0,1308.0,436.0,1128.0,436.0,0.0
5,C1_P02_N1_S5_1.JPG,6,116.0,1592.0,300.0,1592.0,300.0,1904.0,116.0,1904.0,0.0
6,C1_P02_N1_S5_1.JPG,7,1172.0,1104.0,1324.0,1104.0,1324.0,1404.0,1172.0,1404.0,0.0
7,C1_P02_N1_S5_1.JPG,8,1204.0,2072.0,1376.0,2072.0,1376.0,2400.0,1204.0,2400.0,0.0
8,C1_P02_N1_S5_1.JPG,9,1212.0,1608.0,1376.0,1608.0,1376.0,1888.0,1212.0,1888.0,0.0
9,C1_P02_N1_S5_1.JPG,10,1212.0,624.0,1360.0,624.0,1360.0,928.0,1212.0,928.0,0.0
10,C1_P02_N1_S5_1.JPG,11,1308.0,1104.0,1460.0,1104.0,1460.0,1404.0,1308.0,1404.0,0.0
11,C1_P02_N1_S5_1.JPG,12,1308.0,156.0,1488.0,156.0,1488.0,440.0,1308.0,440.0,0.0
12,C1_P02_N1_S5_1.JPG,13,1340.0,628.0,1488.0,628.0,1488.0,932.0,1340.0,932.0,0.0
13,C1_P02_N1_S5_1.JPG,14,1348.0,2068.0,1520.0,2068.0,1520.0,2396.0,1348.0,2396.0,0.0
14,C1_P02_N1_S5_1.JPG,15,1364.0,1608.0,1528.0,1608.0,1528.0,1888.0,1364.0,1888.0,0.0
15,C1_P02_N1_S5_1.JPG,16,140.0,1084.0,304.0,1084.0,304.0,1380.0,140.0,1380.0,0.0
16,C1_P02_N1_S5_1.JPG,17,1428.0,1108.0,1580.0,1108.0,1580.0,1408.0,1428.0,1408.0,0.0
17,C1_P02_N1_S5_1.JPG,18,1472.0,176.0,1652.0,176.0,1652.0,460.0,1472.0,460.0,0.0
18,C1_P02_N1_S5_1.JPG,19,1476.0,652.0,1604.0,652.0,1604.0,936.0,1476.0,936.0,0.0
19,C1_P02_N1_S5_1.JPG,20,1508.0,2056.0,1680.0,2056.0,1680.0,2384.0,1508.0,2384.0,0.0
20,C1_P02_N1_S5_1.JPG,21,152.0,528.0,344.0,528.0,344.0,832.0,152.0,832.0,0.0
21,C1_P02_N1_S5_1.JPG,22,1536.0,1612.0,1700.0,1612.0,1700.0,1892.0,1536.0,1892.0,0.0
22,C1_P02_N1_S5_1.JPG,23,1584.0,1104.0,1728.0,1104.0,1728.0,1404.0,1584.0,1404.0,0.0
23,C1_P02_N1_S5_1.JPG,24,1608.0,652.0,1736.0,652.0,1736.0,936.0,1608.0,936.0,0.0
24,C1_P02_N1_S5_1.JPG,25,188.0,8.0,388.0,8.0,388.0,320.0,188.0,320.0,0.0
25,C1_P02_N1_S5_1.JPG,26,296.0,2076.0,480.0,2076.0,480.0,2416.0,296.0,2416.0,0.0
26,C1_P02_N1_S5_1.JPG,27,308.0,1592.0,492.0,1592.0,492.0,1904.0,308.0,1904.0,0.0
27,C1_P02_N1_S5_1.JPG,28,328.0,1092.0,492.0,1092.0,492.0,1388.0,328.0,1388.0,0.0
28,C1_P02_N1_S5_1.JPG,29,328.0,544.0,524.0,544.0,524.0,848.0,328.0,848.0,0.0
29,C1_P02_N1_S5_1.JPG,30,372.0,36.0,572.0,36.0,572.0,348.0,372.0,348.0,0.0
30,C1_P02_N1_S5_1.JPG,31,484.0,2124.0,668.0,2124.0,668.0,2428.0,484.0,2428.0,0.0
31,C1_P02_N1_S5_1.JPG,32,500.0,1596.0,684.0,1596.0,684.0,1908.0,500.0,1908.0,0.0
32,C1_P02_N1_S5_1.JPG,33,520.0,1092.0,704.0,1092.0,704.0,1388.0,520.0,1388.0,0.0
33,C1_P02_N1_S5_1.JPG,34,524.0,572.0,720.0,572.0,720.0,876.0,524.0,876.0,0.0
34,C1_P02_N1_S5_1.JPG,35,572.0,48.0,772.0,48.0,772.0,360.0,572.0,360.0,0.0
35,C1_P02_N1_S5_1.JPG,36,660.0,2128.0,844.0,2128.0,844.0,2432.0,660.0,2432.0,0.0
36,C1_P02_N1_S5_1.JPG,37,668.0,1600.0,852.0,1600.0,852.0,1912.0,668.0,1912.0,0.0
37,C1_P02_N1_S5_1.JPG,38,696.0,1100.0,880.0,1100.0,880.0,1396.0,696.0,1396.0,0.0
38,C1_P02_N1_S5_1.JPG,39,724.0,584.0,920.0,584.0,920.0,888.0,724.0,888.0,0.0
39,C1_P02_N1_S5_1.JPG,40,760.0,80.0,960.0,80.0,960.0,392.0,760.0,392.0,0.0
40,C1_P02_N1_S5_1.JPG,41,832.0,2076.0,1004.0,2076.0,1004.0,2404.0,832.0,2404.0,0.0
41,C1_P02_N1_S5_1.JPG,42,860.0,1592.0,1044.0,1592.0,1044.0,1904.0,860.0,1904.0,0.0
42,C1_P02_N1_S5_1.JPG,43,868.0,1124.0,1052.0,1124.0,1052.0,1392.0,868.0,1392.0,0.0
43,C1_P02_N1_S5_1.JPG,44,88.0,2072.0,300.0,2072.0,300.0,2412.0,88.0,2412.0,0.0
44,C1_P02_N1_S5_1.JPG,45,908.0,600.0,1104.0,600.0,1104.0,904.0,908.0,904.0,0.0
45,C1_P02_N1_S5_1.JPG,46,932.0,96.0,1132.0,96.0,1132.0,408.0,932.0,408.0,0.0